# Generated by Django 3.2.8 on 2021-10-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_offers_button_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
